apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  namespace: boutique
  labels:
    release: prometheus
spec:
  selector:
    matchExpressions:
      - key: app
        operator: Exists
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - boutique